local-dir: ${{ secrets.local_dir }}on:
  push:
    branches:
      - development
name: ğŸš€ Deploy development
jobs:
  web-deploy:
    name: ğŸ‰ Deploy development
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ğŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_url }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.ftp_dev_path }}
        exclude: "**/public/*"

    - name: ğŸ“ Update assets
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_url }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.ftp_dev_assets_path }}
        
